name: Java CI with Gradle

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 11
        distribution: 'adopt'
    - name: Build with Gradle
      run: ./gradlew build
    - name: Publish to JitPack
      run: ./gradlew publish
